### ISSUE TITLE
Self-tuning PI controller window is cropped

### ISSUE THREAD

**Issue by kmdouglass** [LEB-EPFL/ALICA#10]
The window is cropped even if I increase the size of the panel (see below).

This is on my testing branch for upgrading SASS's version of ALICA to v0.2.4. I do not yet know whether it happens on v0.2.1 as well.

The problem is definitely with ALICA because the JPanel belongs to the ALICA project.

![_016](https://user-images.githubusercontent.com/3697676/32769606-e75c1f8c-c91c-11e7-85f0-e7926f433df8.png)

**Comment by MStefko** [comment]
The problem might be in hardcoded values in lines 90 and 96 of [MonitorGUI.java](https://github.com/LEB-EPFL/ALICA/blob/master/src/ch/epfl/leb/alica/workers/MonitorGUI.java). (A similar problem can then show up with SetupPanels in lines 111 and 120 of [MainGUI.java](https://github.com/LEB-EPFL/ALICA/blob/ce994d38cb333504b0fe5e60cf1c76f41eafe7d7/src/ch/epfl/leb/alica/MainGUI.java#L111).) Try setting the line 96 to `controller_status.setBounds(5,5,300,300);`. This will probably cause misalignment but will point to the source of the problem.

When I was creating the GUI, it took me quite some time to get the dynamic loading of panels based on selected Analyzer/Controller to work (mainly because I had no idea what I was doing). So to make my job a little easier, I constrained the maximal size of these panels. This in retrospect was not the best choice, but handling dynamic loading of GUI elements of arbitrary sizes is not an easy task either. On Windows10 I didn't have this problem because the fonts are narrower so the panel did fit into the original constraints.

**Comment by kmdouglass** [comment]
Thanks for the explanation. I see the problem. I'll probably take another look at the GUI in the future then; for now I think I will just increase the size of the windows ;p

**Comment by kmdouglass** [comment]
A possible solution is to switch to a so-called Card Layout, which is designed exactly for this purpose:
http://vincentramdhanie.blogspot.ch/2009/11/cardlayout-with-netbeans.html?m=1

**Comment by kmdouglass** [comment]
I'm not seeing this anymore, neither on Linux nor on Windows. I don't see it either in ALICA or SASS. Closing for now...
