### ISSUE TITLE
Differences between original SpotCounter and the ALICA implementation

### ISSUE THREAD

**Issue by kmdouglass** [LEB-EPFL/ALICA#11]
In version 0.2.4, Spot Counter (as implemented in ALICA) does not identify spots along the right and bottom part of an image. There is typically an empty region ~10 pixels wide that is simply left undetected.

I have also noticed small differences between which spots are detected when comparing the latest version of the plugin (0.13) to ALICA's implementation.

There should probably be a thorough review of the ALICA spot counter implementation to identify the edge bugs and to make the output the same as the plugin.

**Comment by kmdouglass** [comment]
One major difference appears to be coming from FindLocalMaxima.java and its modification to use a ROI:

### ALICA

```java
// divide the image up in blocks of size n and find local maxima
int n2 = 2*n + 1;
// calculate borders once
int xRealEnd = roi_rect.x + roi_rect.width;
int xEnd = xRealEnd - 2*n2;
int yRealEnd = roi_rect.y + roi_rect.height;
int yEnd = yRealEnd - 2*n2;
for (int i=roi_rect.x + n; i < xEnd; i+=n2) {
  for (int j=roi_rect.y + n; j < yEnd; j+=n2) {
    int mi = i;
    int mj = j;
```

### Spot Counter (original)

```java
// divide the image up in blocks of size n and find local maxima
int n2 = 2*n + 1;
// calculate borders once
int xRealEnd = roi.x + roi.width;
int xEnd = xRealEnd - n;
int yRealEnd = roi.y + roi.height;
int yEnd = yRealEnd - n;
for (int i=roi.x + n/2; i < xEnd; i+=n2) {
  for (int j=roi.y + n/2; j < yEnd; j+=n2) {
    int mi = i;
    int mj = j;
```

**Comment by kmdouglass** [comment]
Changing the ALICA code to match the original from Spot Counter makes the two algorithms agree and fixes the border bug.

@MStefko , was there a reason for why FindLocalMaximum.java was modified as above, or do you think it was a simple typing mistake? Would it be safe to change the offending lines back to the original version, i.e. change ```2*n2``` to ```n``` when defining ```xEnd``` and ```yEnd``` and changing ```n``` to ```n/2``` in the loop?

**Comment by MStefko** [comment]
This is an unexpected consequence of a fix to an issue I had where SpotCounter was mistakenly identifying a lot of spots on the right and bottom edge of the image if no ROI is used. This is because when SpotCounter's identification "box" is too close to the edge of the image, its corners are actually outside of the image. These corner pixels are then assumed to have a value of 0 which causes false positives (since SpotCounter's criterium is that the difference between the center pixel and average of corner pixels is above `noise_tolerance`). You can clearly see this happening also in the original FIJI version of SpotCounter.

So to fix this, I simply reduced the iteration range so that the box never overflows over the edge of the image (or ROI), but it probably has unexpected consequences when a ROI is used. I would recommend carefully reviewing the entire [FindLocalMaxima.FindMax](https://github.com/LEB-EPFL/ALICA/blob/ce994d38cb333504b0fe5e60cf1c76f41eafe7d7/src/ch/epfl/leb/alica/analyzers/spotcounter/FindLocalMaxima.java#L100) function if you want to be sure.

**Comment by kmdouglass** [comment]
OK, thanks. So you're saying that the false positives can appear using the original SpotCounter in a full sized-image without any ROI selected? I haven't noticed this myself, but I have been working primarily with simulated data. I'll try to reproduce this behavior to see if I can better understand the problem.

The problem with the current implementation is that, for very small fields of view (32 x 32 pixels, for example), you lose most of the spots because they lie along these edges ;p

**Comment by MStefko** [comment]
That's weird, SpotCounter should not care about pixels beyond the currently scanned box.

**Comment by kmdouglass** [comment]
For now, I actually reverted SpotCounter back to the original format, but I haven't merged it into the main ALICA repo yet. If it has edge detection issues, I will say that is a problem with the algorithm itself. Personally, though, I haven't had any problems with it. If we want to fix it, then I would probably explicitly write a whole new spot counter with a different name so no one makes the false assumption that ALICA's spot counter should match Nico Stuurman's (like I did).
