### ISSUE TITLE
Incorrect units on the PI controller setup panel?

### ISSUE THREAD

**Issue by kmdouglass** [LEB-EPFL/ALICA#12]
The PI controller setup panel has the I-term in units of 1/s. Should this be 1/frames, @MStefko ?

**Comment by MStefko** [comment]
The `1/s` label is correct. The controller is decoupled from frame acquisition (and the analyzer) via the [ControlWorker](https://github.com/LEB-EPFL/ALICA/blob/ce994d38cb333504b0fe5e60cf1c76f41eafe7d7/src/ch/epfl/leb/alica/workers/ControlWorker.java#L100), which executes the `analysis_worker.queryAnalyzerForBatchOutput()` method at a fixed time rate, regardless of frame acquisition speed. 

This time rate can be set by the user in the GUI under label `Controller tick rate [ms]`, so in order to decouple changes in tick rate from the `I`-term in the PI controller, the user sets the `I`-term in `1/s`, and the conversion to units of `1/ticks` is done internally [here](https://github.com/LEB-EPFL/ALICA/blob/ce994d38cb333504b0fe5e60cf1c76f41eafe7d7/src/ch/epfl/leb/alica/controllers/selftuningpi/SelfTuningController.java#L132).

**Comment by kmdouglass** [comment]
Closing this because there is no problem.
